name: Hunter
version: ${project.version}
main: me.jxng1.hunterminigame.HunterPlugin
api-version: 1.16
authors: [ jxng1 ]
description: Minigame for 1.16 Minecraft.
website: github.com/jxng1
commands:
  start:
    description: Start minigame.
  stop:
    description: Stop minigame.
  createclue:
    description: Create clue for calling player.
  removeclue:
    description: Remove clue for current session.
  leavequeue:
    description: Leave queue for minigame.